# Generated by Django 3.1.6 on 2021-02-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Project.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'time')},
        ),
    ]
